/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/blenderModel.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./blenderStuff/blenderModel.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-5.217, 0.739, 1.026]} rotation={[Math.PI / 2, 0, 0]} scale={0.004}>
        <mesh geometry={nodes.哈工大物联网_1.geometry} material={materials['mat-1']} />
        <mesh geometry={nodes.哈工大物联网_2.geometry} material={materials['mat-2']} />
      </group>
      <group position={[-5.283, 0.925, -0.655]} rotation={[Math.PI / 2, 0, 0]} scale={0.004}>
        <mesh geometry={nodes.哈工大物联网001_1.geometry} material={materials['mat-1']} />
        <mesh geometry={nodes.哈工大物联网001_2.geometry} material={materials['mat-3']} />
        <mesh geometry={nodes.哈工大物联网001_3.geometry} material={materials['mat-4']} />
      </group>
      <mesh geometry={nodes.哈工大物联网002.geometry} material={materials['mat-4']} position={[-5.562, -1.032, -2.526]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
      <mesh geometry={nodes.哈工大物联网003.geometry} material={materials['mat-2']} position={[-5.192, 0.759, 1.258]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
      <group position={[-5.093, 0.626, 1.072]} rotation={[Math.PI / 2, 0, 0]} scale={0.004}>
        <mesh geometry={nodes.哈工大物联网004_1.geometry} material={materials['mat-1']} />
        <mesh geometry={nodes.哈工大物联网004_2.geometry} material={materials['mat-2']} />
        <mesh geometry={nodes.哈工大物联网004_3.geometry} material={materials['mat-4']} />
        <mesh geometry={nodes.哈工大物联网004_4.geometry} material={materials['mat-5']} />
      </group>
      <group position={[-5.249, 0.782, 1.475]} rotation={[Math.PI / 2, 0, 0]} scale={0.004}>
        <mesh geometry={nodes.哈工大物联网006_1.geometry} material={materials['mat-1']} />
        <mesh geometry={nodes.哈工大物联网006_2.geometry} material={materials['mat-2']} />
      </group>
      <mesh geometry={nodes.哈工大物联网008.geometry} material={materials['mat-2']} position={[-5.221, 0.823, 1.133]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
      <mesh geometry={nodes.哈工大物联网005.geometry} material={materials['mat-2']} position={[-5.23, 0.755, 1.152]} rotation={[Math.PI / 2, 0, 0]} scale={0.004} />
      <group position={[-5.221, 0.823, 1.133]} rotation={[Math.PI / 2, 0, 0]} scale={0.004}>
        <mesh geometry={nodes.哈工大物联网009_1.geometry} material={materials['mat-1']} />
        <mesh geometry={nodes.哈工大物联网009_2.geometry} material={materials['mat-2']} />
        <mesh geometry={nodes.哈工大物联网009_3.geometry} material={materials['mat-3']} />
      </group>
      <group position={[-5.221, 0.823, 1.133]} rotation={[Math.PI / 2, 0, 0]} scale={0.004}>
        <mesh geometry={nodes.哈工大物联网010_1.geometry} material={materials['mat-1']} />
        <mesh geometry={nodes.哈工大物联网010_2.geometry} material={materials['mat-3']} />
      </group>
      <group position={[-5.221, 0.823, 1.133]} rotation={[Math.PI / 2, 0, 0]} scale={0.004}>
        <mesh geometry={nodes.哈工大物联网011_1.geometry} material={materials['mat-1']} />
        <mesh geometry={nodes.哈工大物联网011_2.geometry} material={materials['mat-3']} />
      </group>
      <mesh geometry={nodes.柱体.geometry} material={nodes.柱体.material} position={[-4.023, 2.981, -1.449]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.065, -3, -0.065]} />
      <mesh geometry={nodes.柱体001.geometry} material={nodes.柱体001.material} position={[-4.026, 2.981, -3.288]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.065, -3, -0.065]} />
      <mesh geometry={nodes.柱体002.geometry} material={nodes.柱体002.material} position={[0.043, 2.981, -3.276]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.065, -3, -0.065]} />
      <mesh geometry={nodes.柱体003.geometry} material={nodes.柱体003.material} position={[0.04, 2.981, -1.464]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.065, -3, -0.065]} />
      <mesh geometry={nodes.立方体.geometry} material={nodes.立方体.material} position={[-1.987, 1.241, -2.361]} scale={[2.01, 0.09, 0.9]} />
      <mesh geometry={nodes.立方体001.geometry} material={nodes.立方体001.material} position={[-1.987, 3.131, -2.361]} scale={[2.01, 0.09, 0.9]} />
      <mesh geometry={nodes.哈工大物联网011.geometry} material={materials['mat-4']} position={[-7.554, -1.046, -2.508]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
      <mesh geometry={nodes.哈工大物联网012.geometry} material={materials['mat-4']} position={[-5.079, -1.129, -2.624]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
      <mesh geometry={nodes.哈工大物联网013.geometry} material={materials['mat-4']} position={[-7.105, -1.129, -2.666]} rotation={[Math.PI / 2, 0, 0]} scale={0.003} />
      <mesh geometry={nodes.圆环.geometry} material={nodes.圆环.material} position={[0.14, 0.44, 1.51]} rotation={[Math.PI / 2, 0, 0]} scale={[0.995, 0.763, 0.909]} />
      <mesh geometry={nodes.立方体010.geometry} material={nodes.立方体010.material} position={[0.318, 0.074, 0.88]} scale={[0.062, 0.041, 0.551]} />
    </group>
  )
}

useGLTF.preload('./blenderStuff/blenderModel.glb')
