/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/blenderStuff/Model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/blenderStuff/Model.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-135.58, 110.071, -81.187]} rotation={[Math.PI / 2, 0, 0]} scale={0.109}>
        <mesh geometry={nodes.哈工大物联网_1.geometry} material={materials['mat-1']} />
        <mesh geometry={nodes.哈工大物联网_2.geometry} material={materials['mat-2']} />
        <mesh geometry={nodes.哈工大物联网_3.geometry} material={materials['mat-3']} />
        <mesh geometry={nodes.哈工大物联网_4.geometry} material={materials['mat-4']} />
        <mesh geometry={nodes.哈工大物联网_5.geometry} material={materials['mat-5']} />
      </group>
      <group position={[-118.59, 44.436, -209.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.078}>
        <mesh geometry={nodes.哈工大物联网013.geometry} material={materials['mat-1.001']} />
        <mesh geometry={nodes.哈工大物联网013_1.geometry} material={materials['mat-4.001']} />
      </group>
      <group position={[-34.959, -11.769, -86.489]} rotation={[1.571, 0, 1.551]} scale={[25.189, 19.325, 23.012]}>
        <mesh geometry={nodes.圆环002.geometry} material={materials.材质} />
        <mesh geometry={nodes.圆环002_1.geometry} material={materials['材质.001']} />
      </group>
      <group position={[-19.813, 26.048, -98.915]} rotation={[Math.PI / 2, 0, 1.552]} scale={0.104}>
        <mesh geometry={nodes.哈工大物联网001_1.geometry} material={materials['mat-1.002']} />
        <mesh geometry={nodes.哈工大物联网001_2.geometry} material={materials['mat-3.002']} />
        <mesh geometry={nodes.哈工大物联网001_3.geometry} material={materials['mat-4.002']} />
      </group>
      <group position={[-137.677, 109.678, 135.123]} rotation={[Math.PI / 2, 0, 0]} scale={0.109}>
        <mesh geometry={nodes.哈工大物联网005.geometry} material={materials['mat-1.003']} />
        <mesh geometry={nodes.哈工大物联网005_1.geometry} material={materials['mat-2.003']} />
        <mesh geometry={nodes.哈工大物联网005_2.geometry} material={materials['mat-3.003']} />
        <mesh geometry={nodes.哈工大物联网005_3.geometry} material={materials['mat-4.003']} />
        <mesh geometry={nodes.哈工大物联网005_4.geometry} material={materials['mat-5.003']} />
      </group>
      <group position={[151.564, 112.676, -99.131]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.109}>
        <mesh geometry={nodes.哈工大物联网007.geometry} material={materials['mat-1.005']} />
        <mesh geometry={nodes.哈工大物联网007_1.geometry} material={materials['mat-2.005']} />
        <mesh geometry={nodes.哈工大物联网007_2.geometry} material={materials['mat-3.005']} />
        <mesh geometry={nodes.哈工大物联网007_3.geometry} material={materials['mat-4.005']} />
        <mesh geometry={nodes.哈工大物联网007_4.geometry} material={materials['mat-5.005']} />
      </group>
      <mesh geometry={nodes.立方体.geometry} material={materials['材质.012']} position={[113.119, 22.79, 74.72]} scale={-23.822} />
      <mesh geometry={nodes.柱体.geometry} material={materials['材质.009']} position={[94.136, -4.47, 93.817]} scale={3.782} />
      <mesh geometry={nodes.柱体001.geometry} material={materials['材质.011']} position={[94.136, -4.47, 56.021]} scale={3.782} />
      <mesh geometry={nodes.柱体002.geometry} material={materials['材质.010']} position={[131.81, -4.47, 55.899]} scale={3.782} />
      <mesh geometry={nodes.柱体003.geometry} material={materials['材质.008']} position={[131.81, -4.47, 93.329]} scale={3.782} />
      <mesh geometry={nodes.立方体001.geometry} material={materials['材质.003']} position={[113.119, 22.79, 74.72]} scale={-23.822} />
      <mesh geometry={nodes.立方体002.geometry} material={materials['材质.002']} position={[113.119, 70.312, 74.72]} scale={-23.822} />
      <mesh geometry={nodes.立方体003.geometry} material={materials['材质.013']} position={[96.915, 63.73, 73.639]} scale={3.467} />
      <mesh geometry={nodes.立方体006.geometry} material={materials['材质.015']} position={[103.693, 89.208, 65.676]} rotation={[Math.PI / 2, 0, 0]} scale={3.467} />
      <mesh geometry={nodes.立方体004.geometry} material={materials['材质.007']} position={[96.915, 63.73, 73.639]} scale={3.467} />
      <mesh geometry={nodes.立方体005.geometry} material={materials['材质.014']} position={[96.915, 90.155, 73.639]} scale={2.924} />
      <mesh geometry={nodes.柱体004.geometry} material={materials['材质.017']} position={[103.598, 83.152, 92.311]} scale={-3.008} />
      <mesh geometry={nodes.立方体007.geometry} material={materials['材质.016']} position={[103.693, 90.345, 86.725]} rotation={[Math.PI / 2, 0, 0]} scale={3.87} />
      <mesh geometry={nodes.平面.geometry} material={materials['材质.005']} position={[103.587, 59.848, 94.222]} scale={6.031} />
      <mesh geometry={nodes.平面001.geometry} material={materials['材质.004']} position={[118.507, 80.503, 65.216]} rotation={[1.529, 0, 0]} scale={15.773} />
      <mesh geometry={nodes.平面002.geometry} material={materials['材质.006']} position={[120.923, 60.058, 63.462]} scale={6.031} />
      <mesh geometry={nodes.立方体008.geometry} material={nodes.立方体008.material} position={[120.914, 72.654, 62.65]} scale={2.224} />
    </group>
  )
}

useGLTF.preload('/blenderStuff/Model.glb')
