/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/blenderStuff/Model.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/blenderStuff/Model.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-135.58, 110.071, -81.187]} rotation={[Math.PI / 2, 0, 0]} scale={0.109}>
        <mesh geometry={nodes.哈工大物联网_1.geometry} material={materials['mat-1']} />
        <mesh geometry={nodes.哈工大物联网_2.geometry} material={materials['mat-2']} />
        <mesh geometry={nodes.哈工大物联网_3.geometry} material={materials['mat-3']} />
        <mesh geometry={nodes.哈工大物联网_4.geometry} material={materials['mat-4']} />
        <mesh geometry={nodes.哈工大物联网_5.geometry} material={materials['mat-5']} />
      </group>
      <group position={[-118.59, 44.436, -209.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.078}>
        <mesh geometry={nodes.哈工大物联网013.geometry} material={materials['mat-1.001']} />
        <mesh geometry={nodes.哈工大物联网013_1.geometry} material={materials['mat-4.001']} />
      </group>
      <group position={[-34.959, -11.769, -86.489]} rotation={[1.571, 0, 1.551]} scale={[25.189, 19.325, 23.012]}>
        <mesh geometry={nodes.圆环002.geometry} material={materials.材质} />
        <mesh geometry={nodes.圆环002_1.geometry} material={materials['材质.001']} />
      </group>
      <group position={[-19.813, 26.048, -98.915]} rotation={[Math.PI / 2, 0, 1.552]} scale={0.104}>
        <mesh geometry={nodes.哈工大物联网001_1.geometry} material={materials['mat-1.002']} />
        <mesh geometry={nodes.哈工大物联网001_2.geometry} material={materials['mat-3.002']} />
        <mesh geometry={nodes.哈工大物联网001_3.geometry} material={materials['mat-4.002']} />
      </group>
      <group position={[-137.677, 109.678, 135.123]} rotation={[Math.PI / 2, 0, 0]} scale={0.109}>
        <mesh geometry={nodes.哈工大物联网005_1.geometry} material={materials['mat-1.003']} />
        <mesh geometry={nodes.哈工大物联网005_2.geometry} material={materials['mat-2.003']} />
        <mesh geometry={nodes.哈工大物联网005_3.geometry} material={materials['mat-3.003']} />
        <mesh geometry={nodes.哈工大物联网005_4.geometry} material={materials['mat-4.003']} />
        <mesh geometry={nodes.哈工大物联网005_5.geometry} material={materials['mat-5.003']} />
      </group>
      <group position={[-112.685, 38.672, 245.211]} rotation={[Math.PI / 2, 0, 0]} scale={0.078}>
        <mesh geometry={nodes.哈工大物联网006.geometry} material={materials['mat-1.004']} />
        <mesh geometry={nodes.哈工大物联网006_1.geometry} material={materials['mat-4.004']} />
      </group>
      <group position={[151.564, 112.676, -99.131]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.109}>
        <mesh geometry={nodes.哈工大物联网007.geometry} material={materials['mat-1.005']} />
        <mesh geometry={nodes.哈工大物联网007_1.geometry} material={materials['mat-2.005']} />
        <mesh geometry={nodes.哈工大物联网007_2.geometry} material={materials['mat-3.005']} />
        <mesh geometry={nodes.哈工大物联网007_3.geometry} material={materials['mat-4.005']} />
        <mesh geometry={nodes.哈工大物联网007_4.geometry} material={materials['mat-5.005']} />
      </group>
      <group position={[126.572, 41.671, -209.219]} rotation={[Math.PI / 2, 0, Math.PI]} scale={0.078}>
        <mesh geometry={nodes.哈工大物联网008.geometry} material={materials['mat-1.006']} />
        <mesh geometry={nodes.哈工大物联网008_1.geometry} material={materials['mat-4.006']} />
      </group>
    </group>
  )
}

useGLTF.preload('/blenderStuff/Model.glb')
