/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/blenderStuff/Shuilunji.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Shuilunji(props) {
  const { nodes, materials } = useGLTF('/blenderStuff/Shuilunji.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-32.538, 42.017, -21.85]} rotation={[Math.PI, 0, Math.PI]} scale={0.048}>
        <mesh geometry={nodes.蜗壳.geometry} material={materials['210,210,255.009']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.导叶拐臂.geometry} material={materials['210,210,255.007']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.导叶连杆.geometry} material={materials['210,210,255.008']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.主轴.geometry} material={materials['126,162,151']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.基坑里衬.geometry} material={materials['210,210,255.001']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.导叶机.geometry} material={materials['210,210,255']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.尾水管002.geometry} material={materials['225,225,225.017']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['1001'].geometry} material={materials['225,225,225']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['10001'].geometry} material={materials['225,225,225.009']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['11001'].geometry} material={materials['225,225,225.010']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['12001'].geometry} material={materials['225,225,225.011']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['13001'].geometry} material={materials['225,225,225.012']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['14001'].geometry} material={materials['225,225,225.013']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['15001'].geometry} material={materials['225,225,225.014']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['16001'].geometry} material={materials['225,225,225.015']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['2001'].geometry} material={materials['225,225,225.001']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['3001'].geometry} material={materials['225,225,225.002']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['4001'].geometry} material={materials['225,225,225.003']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['5001'].geometry} material={materials['225,225,225.004']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['6001'].geometry} material={materials['225,225,225.005']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['7001'].geometry} material={materials['225,225,225.006']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['8001'].geometry} material={materials['225,225,225.007']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes['9001'].geometry} material={materials['225,225,225.008']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.底环.geometry} material={materials['210,210,255.010']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.合成部分.geometry} material={materials['210,210,255.004']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.合成部分001.geometry} material={materials['243,254,177']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.座环基础.geometry} material={materials['210,210,255.005']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.接力器1.geometry} material={materials['225,225,225.018']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.接力器2.geometry} material={materials['255,128,0.002']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.合成部分002.geometry} material={materials['210,210,255.011']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.合成部分003.geometry} material={materials['255,128,0']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.合成部分004.geometry} material={materials['210,210,255.012']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.合成部分005.geometry} material={materials['255,128,0.001']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.水导轴承.geometry} material={materials['225,225,225.019']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.主轴密封.geometry} material={materials['225,225,225.016']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.脚踏板.geometry} material={materials['210,210,255.002']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.转轮.geometry} material={materials['210,210,255.006']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
        <mesh geometry={nodes.锥管.geometry} material={materials['210,210,255.003']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
      </group>
      <group position={[-32.538, 42.017, -21.85]} rotation={[Math.PI, 0, Math.PI]} scale={0.048}>
        <mesh geometry={nodes['YQSLJ-DG'].geometry} material={materials['225,225,225.020']} position={[-8852.083, -42999.84, 30423.125]} scale={0.745} />
      </group>
    </group>
  )
}

useGLTF.preload('/blenderStuff/Shuilunji.glb')
